[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ffit-daemon"
path = "src/main.rs"

[dependencies]
tonic = "0.14.2"
prost = "0.14.1"

[build-dependencies]
glob = "0.3"
tonic-prost-build = "0.14.2"
